name: lol
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.3.2
  awesome_dialog: ^3.2.1
  font_awesome_flutter: ^10.7.0
  flutter_vector_icons: ^2.0.0
  material_design_icons_flutter: ^7.0.7296
  flutter_fortune_wheel: ^1.3.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  dio: ^5.7.0
  image_picker: ^1.1.2
  meta: ^1.15.0
  hexcolor: ^3.0.1
  url_launcher: ^6.0.20
  flutter_linkify: ^6.0.0
  intl: ^0.19.0
  webview_flutter: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/admin/