name: lol
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  async: ^2.11.0
  awesome_dialog: ^3.2.1
  bloc: ^8.1.4
  carousel_slider: ^5.0.0
  characters: ^1.3.0
  cloud_firestore: ^5.4.2
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  file_picker: ^8.1.2
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.2
  firebase_storage: ^12.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_fortune_wheel: ^1.3.1
  flutter_launcher_icons: ^0.14.1
  flutter_linkify: ^6.0.0
  flutter_vector_icons: ^2.0.0
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  hexcolor: ^3.0.1
  icon_broken: ^1.1.0
  iconly: ^1.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  linkify: ^5.0.0
  material_design_icons_flutter: ^7.0.7296
  meta: ^1.15.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.2.0+3
  string_similarity: ^2.1.1
  url_launcher: ^6.3.0
  webview_flutter: ^4.9.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/tlogo.jpg"
  # remove_alpha_ios: true
  #android-path: "images/icon/App Icon.png"
  # min_sdk_android: 23 # android min sdk min:16, default 21
  adaptive-icon-background: "images/logo.png"
  adaptive-icon-foreground: "images/icons/launcher_icon.png"
